### ISSUE TITLE
Incomplete annotations

### ISSUE THREAD

**Issue by yCobanoglu** [UChicago-Forum-for-Digital-Culture/deepscribe#3]
![deebscribe](https://github.com/edwardclem/deepscribe/assets/56864644/5d9a7142-5f8c-4836-a5c6-f846e521b9a1)
<br>
Many of the images are not annotated completely. This is not a bug right ?

**Comment by edwardclem** [comment]
Nope, that's actually correct - this is why we ended up autocropping some images before training. Some tablets are only partially annotated.
